input.onButtonPressed(Button.A, function () {
    basic.pause(2000)
    cuteBot.motors(30, 0)
    basic.pause(800)
    cuteBot.forward()
    basic.pause(3000)
    cuteBot.moveTime(cuteBot.Direction.left, 100, 4)
    basic.pause(2000)
    cuteBot.motors(0, 30)
    basic.pause(1600)
    cuteBot.forward()
    basic.pause(1000)
    cuteBot.motors(30, 0)
    basic.pause(800)
    cuteBot.forward()
    basic.pause(5000)
    cuteBot.motors(30, 0)
    basic.pause(1600)
    cuteBot.forward()
    basic.pause(6000)
    cuteBot.stopcar()
})
basic.forever(function () {
	
})
